# yaml-language-server: $schema=./azure.schema

trigger:
  branches:
    include:
      - main

pool:
  vmImage: macOS-latest

jobs:
  - job: build
    steps:
      - script: |
          echo export PATH=$GOROOT_1_19_X64/bin:$HOME/go/bin
          export PATH=$GOROOT_1_19_X64/bin:$HOME/go/bin:$PATH

          echo go mod download
          go mod download

          echo go install fyne
          go install fyne.io/fyne/v2/cmd/fyne@latest

          echo fyne package
          fyne package -profile xyz -appID com.example.myapp -appVersion 1.0 -appBuild 1 .

          echo create tar
          tar cvzf $(Build.SourcesDirectory)/macos.tar.gz -C $(Build.SourcesDirectory) $(Build.SourcesDirectory)/voucher.app
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/macos.tar.gz"
          ArtifactName: macos
